@startuml Контекстная диаграмма Агротех C4 v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(агроном, "Агроном", "Использует мобильное приложение")
Person(тепличник, "Тепличный комплекс", "Управление теплицами")
Person(механик, "Механик", "Мониторинг техники")
Person(аналитик, "Аналитик", "Работа с BI-системой")

System(платформа, "АгроПром Х - Цифровая платформа")


Person(дежурныйсотрудник1, "Дежурный сотрудник", "Управление системой 1")
Person(дежурныйсотрудник2, "Дежурный сотрудник", "Управление системой 2")

System(агент1, "Система управления фермой 1")
System(агент2, "Система управления фермой 2")

System(СистемаУправленияФермами, "Система управления фермами")

' === Взаимосвязи ===
Rel(дежурныйсотрудник1, агент1, "Синхронизируется")
Rel(дежурныйсотрудник2, агент2, "Синхронизируется")
Rel(СистемаУправленияФермами, платформа, "Синхронизируется")
Rel(агент1, СистемаУправленияФермами, "Синхронизируется")
Rel(агент2, СистемаУправленияФермами, "Синхронизируется")
Rel(директор, платформа, "Использует")
Rel(агроном, платформа, "Использует")
Rel(тепличник, платформа, "Управляет")
Rel(механик, платформа, "Мониторит")
Rel(аналитик, платформа, "Анализирует")



@enduml