@startuml
title FitLife Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(IOT, "Данные с датчиков") {
  Container(видеокамеры, "Видеокамеры", "JavaScript, React", "Обеспечение пользовательского интерфейса")
  Container(датчикиКормушек, "Датчики кормушек", "IOT sensors", "Сбор данных с кормушек и поилок")
  Container(ДатчикиФильтрацииВоды, "Датчики фильтрации воды", "IOT sensors", "Сбор данных с датчиков фильтров")
}

Container(IOTserver, "IOT server", "IOT server", "Сервер, преобразующий данные")

Container_Boundary(агент1, "Система управления фермой 1") {
  Container(WebApp, "Web Application", "JavaScript, React", "Обеспечение пользовательского интерфейса")
  Container(Backend, "Backend application", "Python, Django", "Выполнение основной логики приложения")
  Container(Database, "Database", "PostgreSQL", "Хранилище данных")

}

Person(дежурныйсотрудник1, "Дежурный сотрудник", "Управление системой 1")

System_Ext(api, "Third-Party API", "Сервис для рассылки уведомлений")

Rel(видеокамеры, IOTserver, "Отправляет")
Rel(IOTserver, Database, "Сохраняет")
Rel(датчикиКормушек, IOTserver, "Отправляет")
Rel(ДатчикиФильтрацииВоды, IOTserver, "Отправляет")
Rel(WebApp, Backend, "Взаимодействует")
Rel(WebApp, видеокамеры, "Транслирует")
Rel(Backend, Database, "Обменивается")
Rel(дежурныйсотрудник1, WebApp, "Взаимодействует")
Rel(Backend, api, "Отправляет")

@enduml